@Shawbrook.FunBooksAndVideos.WebApi_HostAddress = https://localhost:7074

# valid submission (products & membership)
POST {{Shawbrook.FunBooksAndVideos.WebApi_HostAddress}}/api/v1/purchase-order/submit
Accept: application/json
Content-Type: application/json
{
  "customerId": 2,
  "products": [
    {
      "id": 1,
      "quantity": 2
    },
    {
      "id": 2,
      "quantity": 3
    }
  ],
  "membership": {
    "id": 1,
    "type": "Book"
  }
}
###

# valid submission (just products)
POST {{Shawbrook.FunBooksAndVideos.WebApi_HostAddress}}/api/v1/purchase-order/submit
Accept: application/json
Content-Type: application/json
{
  "customerId": 2,
  "products": [
    {
      "id": 1,
      "quantity": 2
    },
    {
      "id": 2,
      "quantity": 3
    }
  ] 
}
###

# valid submission (just membership)
POST {{Shawbrook.FunBooksAndVideos.WebApi_HostAddress}}/api/v1/purchase-order/submit
Accept: application/json
Content-Type: application/json
{
  "customerId": 2,
  "membership": {
    "id": 1,
    "type": "Book"
  }
}
###

# Not found customer
POST {{Shawbrook.FunBooksAndVideos.WebApi_HostAddress}}/api/v1/purchase-order/submit
Accept: application/json
Content-Type: application/json
{
  "customerId": 5,
  "products": [
    {
      "id": 1,
      "quantity": 2
    },
    {
      "id": 2,
      "quantity": 3
    }
  ],
  "membership": {
    "id": 1,
    "type": "Book"
  }
}
###

# Not found product
POST {{Shawbrook.FunBooksAndVideos.WebApi_HostAddress}}/api/v1/purchase-order/submit
Accept: application/json
Content-Type: application/json
{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "quantity": 2
    },
    {
      "id": 5,
      "quantity": 3
    }
  ],
  "membership": {
    "id": 1,
    "type": "Book"
  }
}
###

# Not found membership
POST {{Shawbrook.FunBooksAndVideos.WebApi_HostAddress}}/api/v1/purchase-order/submit
Accept: application/json
Content-Type: application/json
{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "quantity": 2
    },
    {
      "id": 1,
      "quantity": 3
    }
  ],
  "membership": {
    "id": 5,
    "type": "Book"
  }
}
###


# get new purchase order
GET {{Shawbrook.FunBooksAndVideos.WebApi_HostAddress}}/api/v1/purchase-order/1
Accept: application/json
Content-Type: application/json
###

